"""The dual-arm solver: convergence, the shared torso, holds, limits and failures.

Skipped when the optional ``kinematics`` extra is absent.
"""

from __future__ import annotations

from typing import Dict

import numpy as np
import pytest

pytest.importorskip("pink", reason="needs the 'kinematics' optional extra")

from robopy.control.types import (  # noqa: E402
    DualArmTarget,
    JointState,
    TorsoPolicy,
    monotonic_ns,
)
from robopy.kinematics.dual_arm_ik import (  # noqa: E402
    DualArmIK,
    DualArmIKConfig,
    DualArmIKStatus,
)
from robopy.kinematics.synthetic_dual_arm import (  # noqa: E402
    SYNTHETIC_ARM_JOINTS,
    SYNTHETIC_HEAD_JOINTS,
    SYNTHETIC_TORSO_JOINT,
)
from robopy.kinematics.urdf_model import WholeBodyModel  # noqa: E402

DT = 0.01

# Numerical acceptance for the solver, against the synthetic fixture. It says
# the software converges; it says nothing about accuracy on real hardware,
# which depends on calibration and on a measured TCP offset.
POSITION_TOLERANCE_M = 1e-3
ORIENTATION_TOLERANCE_RAD = 1e-2


def _state(
    model: WholeBodyModel,
    positions: Dict[str, float],
    *,
    generation: int = 1,
    age_ns: int = 0,
    valid: bool = True,
) -> JointState:
    names = tuple(model.movable_joint_names)
    now = monotonic_ns() - age_ns
    return JointState(
        joint_names=names,
        position_rad=np.asarray([positions[n] for n in names]),
        velocity_rad_s=np.zeros(len(names)),
        current_a=np.zeros(len(names)),
        valid=np.full(len(names), valid),
        read_start_ns=now,
        read_end_ns=now,
        sequence=0,
        mode_generation=generation,
    )


def _zero(model: WholeBodyModel) -> Dict[str, float]:
    return {name: 0.0 for name in model.movable_joint_names}


def _reachable_targets(model: WholeBodyModel) -> tuple[np.ndarray, np.ndarray, Dict[str, float]]:
    """Targets generated by forward kinematics, so they are reachable by construction."""
    goal = _zero(model)
    goal.update(
        {
            "shoulder_roll_left_dof": 0.35,
            "elbow_pitch_left_dof": -0.5,
            "shoulder_roll_right_dof": -0.35,
            "elbow_pitch_right_dof": -0.5,
            SYNTHETIC_TORSO_JOINT: 0.25,
        }
    )
    q = model.q_from_positions(goal)
    return model.frame_pose(q, "left_tcp"), model.frame_pose(q, "right_tcp"), goal


def _run(ik, model, target, *, steps=400, start=None):  # type: ignore[no-untyped-def]
    """Iterate the solver to convergence, returning the pose and last result."""
    current = dict(start or _zero(model))
    result = None
    for _ in range(steps):
        result = ik.solve_step(_state(model, current), target, DT)
        if not result.is_commandable:
            return current, result
        current.update(result.joint_targets_rad)
        if result.status is DualArmIKStatus.CONVERGED:
            break
    return current, result


class TestConvergence:
    def test_both_hands_reach_a_forward_kinematics_generated_target(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        target = DualArmTarget(
            left_target=left, right_target=right, torso_policy=TorsoPolicy.OPTIMIZE
        )
        final, result = _run(dual_arm_ik, whole_body_model, target)

        assert result.status is DualArmIKStatus.CONVERGED
        assert result.left_position_error_m < POSITION_TOLERANCE_M
        assert result.right_position_error_m < POSITION_TOLERANCE_M
        assert result.left_orientation_error_rad < ORIENTATION_TOLERANCE_RAD
        assert result.right_orientation_error_rad < ORIENTATION_TOLERANCE_RAD

        q = whole_body_model.q_from_positions(final)
        np.testing.assert_allclose(
            whole_body_model.frame_pose(q, "left_tcp")[:3, 3], left[:3, 3], atol=1e-3
        )

    def test_the_solver_only_commands_the_thirteen_active_joints(self, dual_arm_ik) -> None:
        assert dual_arm_ik.active_joints == (
            (SYNTHETIC_TORSO_JOINT,)
            + SYNTHETIC_ARM_JOINTS["left"]
            + SYNTHETIC_ARM_JOINTS["right"]
        )
        assert len(dual_arm_ik.active_joints) == 13

    def test_the_head_never_receives_a_command(self, dual_arm_ik, whole_body_model) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        target = DualArmTarget(
            left_target=left, right_target=right, torso_policy=TorsoPolicy.OPTIMIZE
        )
        start = _zero(whole_body_model)
        start[SYNTHETIC_HEAD_JOINTS[0]] = 0.4
        final, result = _run(dual_arm_ik, whole_body_model, target, start=start)

        for name in SYNTHETIC_HEAD_JOINTS:
            assert name not in result.joint_targets_rad
            assert name not in result.joint_velocities_rad_s
        # The head keeps the angle it was measured at.
        assert final[SYNTHETIC_HEAD_JOINTS[0]] == pytest.approx(0.4)

    def test_a_head_angle_still_enters_the_model(self, dual_arm_ik, whole_body_model) -> None:
        # The head is not a decision variable, but its measured angle is
        # required, because it moves the collision geometry.
        left, right, _ = _reachable_targets(whole_body_model)
        incomplete = {
            name: 0.0
            for name in whole_body_model.movable_joint_names
            if name not in SYNTHETIC_HEAD_JOINTS
        }
        names = tuple(incomplete)
        state = JointState(
            joint_names=names,
            position_rad=np.zeros(len(names)),
            velocity_rad_s=np.zeros(len(names)),
            current_a=np.zeros(len(names)),
            valid=np.ones(len(names), dtype=bool),
            read_start_ns=monotonic_ns(),
            read_end_ns=monotonic_ns(),
            sequence=0,
            mode_generation=1,
        )
        result = dual_arm_ik.solve_step(
            state, DualArmTarget(left_target=left, right_target=right), DT
        )
        assert result.status is DualArmIKStatus.SOLVER_ERROR
        assert "collision geometry" in result.message


class TestTorsoPolicies:
    def test_fixed_holds_the_torso_exactly(self, dual_arm_ik, whole_body_model) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        target = DualArmTarget(
            left_target=left, right_target=right, torso_policy=TorsoPolicy.FIXED
        )
        final, result = _run(dual_arm_ik, whole_body_model, target, steps=60)
        assert final[SYNTHETIC_TORSO_JOINT] == pytest.approx(0.0, abs=1e-12)
        assert result.torso_velocity_rad_s == pytest.approx(0.0, abs=1e-12)

    def test_optimize_lets_the_torso_move(self, dual_arm_ik, whole_body_model) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        target = DualArmTarget(
            left_target=left, right_target=right, torso_policy=TorsoPolicy.OPTIMIZE
        )
        final, _ = _run(dual_arm_ik, whole_body_model, target)
        assert abs(final[SYNTHETIC_TORSO_JOINT]) > 1e-3

    def test_manual_applies_the_commanded_torso_velocity(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        target = DualArmTarget(
            left_target=left,
            right_target=right,
            torso_policy=TorsoPolicy.MANUAL,
            torso_velocity_rad_s=0.5,
        )
        current = _zero(whole_body_model)
        for _ in range(20):
            result = dual_arm_ik.solve_step(_state(whole_body_model, current), target, DT)
            assert result.is_commandable
            current.update(result.joint_targets_rad)
        # Twenty cycles of 0.5 rad/s over 10 ms each.
        assert current[SYNTHETIC_TORSO_JOINT] == pytest.approx(0.1, abs=1e-6)
        assert result.torso_velocity_rad_s == pytest.approx(0.5)

    def test_a_torso_velocity_outside_manual_policy_is_refused(self) -> None:
        with pytest.raises(ValueError, match="only meaningful with TorsoPolicy.MANUAL"):
            DualArmTarget(
                left_target=np.eye(4),
                right_target=np.eye(4),
                torso_policy=TorsoPolicy.FIXED,
                torso_velocity_rad_s=0.5,
            )

    def test_a_manual_torso_step_beyond_its_limit_is_refused(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        start = _zero(whole_body_model)
        start[SYNTHETIC_TORSO_JOINT] = 1.49  # the soft limit is 1.5 rad
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, start),
            DualArmTarget(
                left_target=left,
                right_target=right,
                torso_policy=TorsoPolicy.MANUAL,
                torso_velocity_rad_s=5.0,
            ),
            DT,
        )
        assert result.status is DualArmIKStatus.INFEASIBLE
        assert "outside" in result.message


class TestHolding:
    def test_a_non_driven_hand_is_held_near_where_it_started(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        left, _right, _ = _reachable_targets(whole_body_model)
        start = _zero(whole_body_model)
        held_before = whole_body_model.frame_pose(
            whole_body_model.q_from_positions(start), "right_tcp"
        )[:3, 3].copy()

        target = DualArmTarget(
            left_target=left,
            right_enabled=False,
            torso_policy=TorsoPolicy.OPTIMIZE,
        )
        final, result = _run(dual_arm_ik, whole_body_model, target, steps=120, start=start)
        held_after = whole_body_model.frame_pose(
            whole_body_model.q_from_positions(final), "right_tcp"
        )[:3, 3]

        assert np.linalg.norm(held_after - held_before) < 5e-3
        # A weighted hold is reported as a residual, not described as a lock.
        assert result.right_hold_residual_m is not None
        assert result.right_position_error_m is None

    def test_the_hold_target_is_latched_and_does_not_follow_the_measurement(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        left, _right, _ = _reachable_targets(whole_body_model)
        target = DualArmTarget(
            left_target=left, right_enabled=False, torso_policy=TorsoPolicy.FIXED
        )
        start = _zero(whole_body_model)
        dual_arm_ik.solve_step(_state(whole_body_model, start), target, DT)

        # Move the right arm by hand. A latched hold keeps pulling it back, so
        # the residual grows; an overwritten hold would report roughly zero.
        pushed = dict(start)
        pushed["elbow_pitch_right_dof"] = 0.4
        result = dual_arm_ik.solve_step(_state(whole_body_model, pushed), target, DT)
        assert result.right_hold_residual_m > 0.01

    def test_rebaselining_recaptures_the_hold_target(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        left, _right, _ = _reachable_targets(whole_body_model)
        start = _zero(whole_body_model)
        dual_arm_ik.solve_step(
            _state(whole_body_model, start),
            DualArmTarget(left_target=left, right_enabled=False),
            DT,
        )
        pushed = dict(start)
        pushed["elbow_pitch_right_dof"] = 0.4
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, pushed),
            DualArmTarget(left_target=left, right_enabled=False, rebaseline=True),
            DT,
        )
        assert result.right_hold_residual_m == pytest.approx(0.0, abs=1e-9)

    def test_reset_clears_the_hold_target(self, dual_arm_ik, whole_body_model) -> None:
        left, _right, _ = _reachable_targets(whole_body_model)
        target = DualArmTarget(left_target=left, right_enabled=False)
        start = _zero(whole_body_model)
        dual_arm_ik.solve_step(_state(whole_body_model, start), target, DT)
        dual_arm_ik.reset()
        pushed = dict(start)
        pushed["elbow_pitch_right_dof"] = 0.4
        result = dual_arm_ik.solve_step(_state(whole_body_model, pushed), target, DT)
        assert result.right_hold_residual_m == pytest.approx(0.0, abs=1e-9)

    def test_enabling_a_side_without_a_target_is_refused(self) -> None:
        with pytest.raises(ValueError, match="left_enabled is True but left_target is None"):
            DualArmTarget(left_target=None, right_target=np.eye(4))


class TestConstraints:
    def test_the_step_is_bounded_by_the_velocity_limit(
        self, whole_body_model, dual_arm_ik
    ) -> None:
        far = np.eye(4)
        far[:3, 3] = [1.0, 0.6, 0.4]
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model)),
            DualArmTarget(left_target=far, right_target=far.copy()),
            DT,
        )
        assert result.is_commandable
        limit = dual_arm_ik.config.max_joint_velocity_rad_s * DT
        for velocity in result.joint_velocities_rad_s.values():
            assert abs(velocity * DT) <= limit + 1e-9

    def test_the_joint_step_ceiling_is_respected(self, whole_body_model, dual_arm_ik) -> None:
        far = np.eye(4)
        far[:3, 3] = [1.0, 0.6, 0.4]
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model)),
            DualArmTarget(left_target=far, right_target=far.copy()),
            DT,
        )
        for name, angle in result.joint_targets_rad.items():
            assert abs(angle) <= dual_arm_ik.config.max_joint_step_rad + 1e-9, name
        assert result.active_limits  # the bounds did clip

    def test_position_limits_are_respected_and_reported(
        self, whole_body_model, dual_arm_ik
    ) -> None:
        far = np.eye(4)
        far[:3, 3] = [0.0, 1.5, 0.4]
        start = _zero(whole_body_model)
        start["shoulder_roll_left_dof"] = 2.55  # the URDF limit is 2.6 rad
        current = dict(start)
        for _ in range(30):
            result = dual_arm_ik.solve_step(
                _state(whole_body_model, current),
                DualArmTarget(left_target=far, right_enabled=False),
                DT,
            )
            if not result.is_commandable:
                break
            current.update(result.joint_targets_rad)
        margin = dual_arm_ik.config.position_limit_margin_rad
        assert current["shoulder_roll_left_dof"] <= 2.6 - margin + 1e-9

    def test_a_configuration_already_outside_its_limits_is_infeasible(
        self, whole_body_model, dual_arm_ik
    ) -> None:
        start = _zero(whole_body_model)
        start["shoulder_roll_left_dof"] = 3.0  # beyond the 2.6 rad URDF limit
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, start),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            DT,
        )
        assert result.status is DualArmIKStatus.INFEASIBLE
        assert result.joint_targets_rad == {}

    def test_a_continuous_joint_without_a_soft_limit_is_refused_at_construction(
        self, synthetic_urdf
    ) -> None:
        model = WholeBodyModel.from_urdf(synthetic_urdf)
        offset = np.eye(4)
        model.add_fixed_frame("left_tcp", "gripper_left_dof", offset)
        model.add_fixed_frame("right_tcp", "gripper_right_dof", offset)
        with pytest.raises(ValueError, match="no finite position limit"):
            DualArmIK(
                model,
                left_frame="left_tcp",
                right_frame="right_tcp",
                torso_joint=SYNTHETIC_TORSO_JOINT,
                left_arm_joints=SYNTHETIC_ARM_JOINTS["left"],
                right_arm_joints=SYNTHETIC_ARM_JOINTS["right"],
            )


class TestCollisionAvoidance:
    def test_a_target_behind_the_torso_does_not_produce_a_colliding_step(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        # Driving the left hand into the torso: the solver must either stop
        # short or refuse, never hand back a step that passes through contact.
        into_torso = whole_body_model.frame_pose(
            whole_body_model.q_from_positions(
                {**_zero(whole_body_model), "shoulder_roll_left_dof": -0.9}
            ),
            "left_tcp",
        )
        current = _zero(whole_body_model)
        for _ in range(200):
            result = dual_arm_ik.solve_step(
                _state(whole_body_model, current),
                DualArmTarget(left_target=into_torso, right_enabled=False),
                DT,
            )
            if not result.is_commandable:
                assert result.status in (
                    DualArmIKStatus.INFEASIBLE,
                    DualArmIKStatus.COLLISION_AT_START,
                )
                break
            assert result.min_collision_distance_m >= 0.0
            current.update(result.joint_targets_rad)

        final = whole_body_model.collision_report(whole_body_model.q_from_positions(current))
        assert final.min_distance >= 0.0

    def test_starting_in_collision_is_reported_rather_than_linearised(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        colliding = _zero(whole_body_model)
        colliding["shoulder_roll_left_dof"] = -0.6
        colliding["shoulder_roll_right_dof"] = 0.6
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, colliding),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            DT,
        )
        assert result.status is DualArmIKStatus.COLLISION_AT_START
        assert result.min_collision_distance_m < 0.0
        assert result.joint_targets_rad == {}


class TestFailureModes:
    def test_a_stale_state_produces_no_command(self, dual_arm_ik, whole_body_model) -> None:
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model), age_ns=10_000_000_000),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            DT,
        )
        assert result.status is DualArmIKStatus.STALE_STATE
        assert not result.is_commandable

    def test_an_invalid_joint_produces_no_command(self, dual_arm_ik, whole_body_model) -> None:
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model), valid=False),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            DT,
        )
        assert result.status is DualArmIKStatus.STALE_STATE

    def test_an_expired_target_produces_no_command(self, dual_arm_ik, whole_body_model) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model)),
            DualArmTarget(
                left_target=left, right_target=right, expiry_ns=monotonic_ns() - 1_000_000
            ),
            DT,
        )
        assert result.status is DualArmIKStatus.STALE_STATE
        assert "expiry" in result.message

    def test_a_non_positive_dt_is_an_error_not_a_command(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model)),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            0.0,
        )
        assert result.status is DualArmIKStatus.SOLVER_ERROR

    def test_exceeding_the_compute_budget_is_reported(
        self, whole_body_model, dual_arm_ik
    ) -> None:
        dual_arm_ik.config.compute_budget_s = 0.0
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model)),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            DT,
        )
        assert result.status is DualArmIKStatus.DEADLINE_EXCEEDED
        assert not result.is_commandable

    def test_the_generation_is_carried_through_to_the_result(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        left, right, _ = _reachable_targets(whole_body_model)
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model), generation=7),
            DualArmTarget(left_target=left, right_target=right),
            DT,
        )
        assert result.generation == 7

    def test_an_unknown_tcp_frame_is_refused_at_construction(self, whole_body_model) -> None:
        with pytest.raises(KeyError, match="does not exist"):
            DualArmIK(
                whole_body_model,
                left_frame="nope_tcp",
                right_frame="right_tcp",
                torso_joint=SYNTHETIC_TORSO_JOINT,
                left_arm_joints=SYNTHETIC_ARM_JOINTS["left"],
                right_arm_joints=SYNTHETIC_ARM_JOINTS["right"],
                config=DualArmIKConfig(require_soft_limits=False),
            )

    def test_a_joint_in_two_groups_is_refused(self, whole_body_model) -> None:
        with pytest.raises(ValueError, match="appears in both"):
            DualArmIK(
                whole_body_model,
                left_frame="left_tcp",
                right_frame="right_tcp",
                torso_joint=SYNTHETIC_TORSO_JOINT,
                left_arm_joints=SYNTHETIC_ARM_JOINTS["left"],
                right_arm_joints=(SYNTHETIC_ARM_JOINTS["left"][0],)
                + SYNTHETIC_ARM_JOINTS["right"][1:],
                config=DualArmIKConfig(require_soft_limits=False),
            )


class TestBoundsInteraction:
    """Found on the real model: ``elbow_pitch_right_dof`` has its upper limit at
    exactly 0.0, so the CAD zero pose sits on the limit. Approaching that limit
    with the acceleration bound active used to empty the feasible set -- the
    solver said "infeasible" when the right answer was "decelerate".
    """

    def test_a_joint_approaching_its_limit_can_always_decelerate(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        # Put a soft limit right above the current angle and drive toward it.
        whole_body_model.set_soft_limits({"elbow_yaw_left_dof": (-2.8, 0.03)})
        target = np.eye(4)
        target[:3, 3] = [0.5, 0.6, 0.4]  # pulls the left arm around, through the limit

        current = _zero(whole_body_model)
        for _ in range(40):
            result = dual_arm_ik.solve_step(
                _state(whole_body_model, current),
                DualArmTarget(left_target=target, right_enabled=False),
                DT,
            )
            assert result.is_commandable, (result.status, result.message)
            current.update(result.joint_targets_rad)
            margin = dual_arm_ik.config.position_limit_margin_rad
            assert current["elbow_yaw_left_dof"] <= 0.03 - margin + 1e-9

    def test_the_acceleration_bound_still_shapes_a_free_step(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        far = np.eye(4)
        far[:3, 3] = [1.0, 0.6, 0.4]
        target = DualArmTarget(left_target=far, right_target=far.copy())
        current = _zero(whole_body_model)
        steps = []
        for _ in range(3):
            result = dual_arm_ik.solve_step(_state(whole_body_model, current), target, DT)
            assert result.is_commandable
            steps.append(dict(result.joint_velocities_rad_s))
            current.update(result.joint_targets_rad)
        a_max = dual_arm_ik.config.max_joint_acceleration_rad_s2
        for name in steps[0]:
            delta_v = abs(steps[1][name] - steps[0][name])
            assert delta_v <= a_max * DT + 1e-6, name

    def test_a_configuration_on_the_limit_itself_reports_infeasible_once(
        self, dual_arm_ik, whole_body_model
    ) -> None:
        # Exactly the real-model situation: the current angle equals the
        # upper limit, so with a margin it is already outside.
        whole_body_model.set_soft_limits({"elbow_yaw_left_dof": (-2.8, 0.0)})
        start = _zero(whole_body_model)
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, start),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            DT,
        )
        # Sitting on the limit is inside [lower, upper] but outside the
        # margin; the solver may only move *away* from it, never refuse.
        assert result.is_commandable, result.message
        assert result.joint_targets_rad["elbow_yaw_left_dof"] <= 0.0


class TestCollisionDiagnostics:
    def test_an_infeasible_collision_step_names_the_offending_pairs(
        self, whole_body_model, dual_arm_ik
    ) -> None:
        # Safety distance far larger than the resting clearances: every pair is
        # "too close" at once, which is unsatisfiable, and the message must say
        # which pairs rather than only that the QP failed.
        dual_arm_ik.config.collision_safety_distance_m = 0.5
        dual_arm_ik.config.collision_activation_distance_m = 0.6
        result = dual_arm_ik.solve_step(
            _state(whole_body_model, _zero(whole_body_model)),
            DualArmTarget(left_target=np.eye(4), right_target=np.eye(4)),
            DT,
        )
        assert result.status is DualArmIKStatus.INFEASIBLE
        assert "inside the 500 mm safety distance" in result.message
        assert "<->" in result.message
        assert "exclusion to record" in result.message
