"""Where these examples are filmed: the ground, the sky, and the lights.

Every task in ``tasks/`` used to build its own bare :class:`ScenarioCfg`, which
meant every task got MetaSim's defaults: a grey checker plane, no sky, and
MuJoCo's camera headlight.  A headlight lights whatever the camera is pointed
at, from where the camera is, and casts no shadows, so nothing in the frame had
a lit side or a dark side and the background was ``#000000``.  That is what
these scenes looked like, and it is why they are all routed through
:func:`staged` now.

Two things live here, and they are separate on purpose:

``room()``
    The floor and the sky, as an asset.  There is one per backend --
    ``calvin_room.xml`` for MuJoCo, ``calvin_room.usda`` for Isaac Sim -- and
    ``assets/calvin_room/README.md`` says why the floor is CALVIN's own.

:data:`LIGHTS`
    The lighting, as configuration rather than as an asset.  MetaSim's light
    configs are written in UsdLux terms and each backend translates them: Isaac
    Sim builds the actual UsdLux prims, MuJoCo approximates them with
    fixed-function OpenGL lights (``metasim/sim/mujoco/lights.py`` documents the
    mapping and its fitted exposure constants).  Writing the rig here rather
    than as ``<light>`` elements in the MJCF is what makes one scene light the
    same way under ``--sim mujoco`` and ``--sim isaacsim``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from metasim.scenario.lights import BaseLightCfg, DistantLightCfg, DomeLightCfg
from metasim.scenario.scenario import ScenarioCfg
from metasim.scenario.scene import SceneCfg
from metasim.scenario.simulator_params import SimParamCfg

from calvin_room_asset import find_calvin_room

__all__ = ["LIGHTS", "SIM_PARAMS", "room", "staged"]

#: Where the room assets live.  Scenery for an example, so they sit beside the
#: example rather than in robopy's package data.
_ROOM = find_calvin_room() or (Path(__file__).resolve().parent / "assets" / "calvin_room")


def room() -> SceneCfg:
    """The ground and the sky, as MetaSim's ``scene``.

    Both files are mandatory, not one or the other.  MetaSim converts an
    object's or a robot's asset to USD on demand, but *not* a scene's:
    ``IsaacsimHandler._load_scene`` reads ``usd_path`` and gives up if it is
    ``None`` -- and because ``scene`` is then not ``None``, the handler does not
    build its own terrain either, so the scene would come up with no floor at
    all and everything in it would fall through the world.

    Any task using this must also pass ``add_default_ground=False``, which
    :func:`staged` does: MetaSim's stock floor is a plane at the same z and the
    two would z-fight.

    Returns:
        The scene config.

    Raises:
        FileNotFoundError: If either file is missing.  The USD is generated, so
            a fresh checkout has to run ``calvin_room_asset.py`` once.
    """
    mjcf = _ROOM / "calvin_room.xml"
    usd = _ROOM / "calvin_room.usda"
    for path in (mjcf, usd):
        if not path.is_file():
            raise FileNotFoundError(
                f"the room is missing at {path}; the MJCF is checked in beside this "
                "example and the USD is generated by "
                "`python examples/roboverse/calvin_room_asset.py`"
            )
    return SceneCfg(name="calvin_room", mjcf_path=str(mjcf), usd_path=str(usd))


#: The lighting, written once for every backend.
#:
#: Three lights, which is one more than a bare scene needs and four fewer than
#: MuJoCo's classic renderer can evaluate:
#:
#: - a **dome** for the sky, which is what stops faces turned away from the key
#:   light going black;
#: - a **key** from high and to the right-front of the bench, the side the
#:   scene cameras look from, so the bench front and the robot's near arm are
#:   the lit faces;
#: - a **fill** from the opposite side at a quarter of the intensity, to keep
#:   the drawer front and the far arm readable without flattening the key.
#:
#: Intensities are in UsdLux candela and were chosen against MuJoCo's fitted
#: constants: the key maps to ``diffuse`` 0.76, the dome to global ambient 0.18,
#: and the total ambient lands near 0.33 -- lit, and still short of clipping.
#: Isaac Sim reads the same numbers as real UsdLux intensities, where they mean
#: what they say; expect the two renders to differ in the way a path tracer
#: differs from OpenGL, not in where the light comes from.
LIGHTS: list[BaseLightCfg] = [
    DomeLightCfg(name="calvin_sky", intensity=400.0, color=(0.82, 0.87, 0.95)),
    DistantLightCfg(
        name="calvin_key", intensity=1600.0, color=(1.0, 0.97, 0.92), polar=30.0, azimuth=45.0
    ),
    DistantLightCfg(
        name="calvin_fill", intensity=420.0, color=(0.88, 0.92, 1.0), polar=35.0, azimuth=-120.0
    ),
]

#: Simulation parameters shared by every task here.
#:
#: ``mujoco_use_scenario_lights`` is the opt-in that makes the MuJoCo backend
#: read :data:`LIGHTS` at all.  It is off by MetaSim's default because
#: ``ScenarioCfg.lights`` has a value whether or not anyone meant it, and
#: honouring that for every scenario in the tree would re-light all of them.
SIM_PARAMS = SimParamCfg(dt=0.005, mujoco_use_scenario_lights=True)


def staged(objects: Sequence, robots: Sequence, **overrides) -> ScenarioCfg:
    """A :class:`ScenarioCfg` standing in :func:`room`, lit by :data:`LIGHTS`.

    Args:
        objects: The scenario's objects.
        robots: The scenario's robots.
        **overrides: Anything else ``ScenarioCfg`` takes, or a different value
            for one of the defaults below.

    Returns:
        The scenario.
    """
    settings = {
        "objects": list(objects),
        "robots": list(robots),
        "scene": room(),
        "add_default_ground": False,  # the room brings its own floor
        "lights": LIGHTS,
        "simulator": "mujoco",
        "sim_params": SIM_PARAMS,
        "decimation": 4,
        "num_envs": 1,
        "headless": True,
    }
    settings.update(overrides)
    return ScenarioCfg(**settings)
